### ISSUE TITLE
`updateChangelog` does nothing if `isReleaseCandidate` is `false`

### ISSUE THREAD

**Issue by mcmire** [MetaMask/auto-changelog#180]
`updateChangelog` seems to have been changed in https://github.com/MetaMask/auto-changelog/pull/158 such that it does nothing if `isReleaseCandidate` is `false`.

Curiously, these changes did not cause the tests to fail. That could indicate some missing test cases. We should add the missing tests and revert the behavior. It would also be helpful to go back and update the changelog entry for this PR and indicate that the change was breaking.

**Comment by desi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Shared-Libraries-621e46b4d7103800171d1b02/issues/MetaMask/auto-changelog/180?planning-poker) with Zenhub @cryptodev-2s @Gudahtt @MajorLift @mcmire @mikesposito

**Comment by Gudahtt** [comment]
Could we update this issue to describe the problem, rather than the solution? The problem I think is that the `update` command always results in zero updates when `--rc` is omitted.

**Comment by mcmire** [comment]
Yes, that's right. I've updated the PR description to match.
