### ISSUE TITLE
Allow sub-bullets in change lists

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/auto-changelog#38]
Is there any reason not to allow this? There are no sub-bullets in the example in [the spec](https://keepachangelog.com/en/1.0.0/), but also nothing forbidding their existence.

```
### Changed

- #6: Bla bla bla
  - Details
```

Currently, `auto-changelog validate` will error on `  - Details`.

**Comment by Gudahtt** [comment]
This was a mistake. It might actually require that each changelog entry is a single line? I'll investigate.

**Comment by Gudahtt** [comment]
I didn't intend #45 to close this. Re-opening.
