### ISSUE TITLE
Disagreements with Prettier

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/auto-changelog#50]
We've started to lint our Markdown files with Prettier, and Prettier overwrites some of the changes applied by this tool. So far, I've confirmed:

- `Unreleased` links
  - Prettier: `[unreleased]: `
  - This tool: `[Unreleased]:`

Related: In #39 I had a malformed `Unrelreased` URL. I also though the lowercasing of the first letter was an error, but that was actually due to me running `yarn lint:fix`, which ran `prettier` on my Markdown files.

**Comment by Gudahtt** [comment]
Looks like this is a Prettier bug: https://github.com/prettier/prettier/issues/3835

**Comment by mcmire** [comment]
Is this an issue anymore?

**Comment by mcmire** [comment]
I think this bug has been fixed in Prettier, because I haven't run into it myself. Closing.
